name: UofT Library Job Monitor

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the action to commit and push changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for existing job data
      run: |
        if [ -f "Jobs-Library/known_jobs.json" ]; then
          echo "Previous job data found in repository"
          ls -la Jobs-Library/known_jobs.json
        else
          echo "No previous job data found - starting fresh"
        fi
    
    - name: Run job monitor
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        USE_SSL: ${{ secrets.USE_SSL }}
      run: |
        cd Jobs-Library
        python notifier_ci.py
    
    - name: Commit job data changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Jobs-Library/known_jobs.json
        git diff --staged --quiet || git commit -m "Update job monitoring data [skip ci]"
        git push
      continue-on-error: true
    
    - name: Upload logs for debugging
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-monitor-logs-${{ github.run_number }}
        path: Jobs-Library/job_monitor.log
        retention-days: 7
