name: UofT Library Job Monitor

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download previous job data
      uses: actions/download-artifact@v3
      with:
        name: job-data
        path: Jobs-Library/
      continue-on-error: true
    
    - name: Run job monitor
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        USE_SSL: ${{ secrets.USE_SSL }}
      run: |
        cd Jobs-Library
        python notifier_ci.py
    
    - name: Upload job data
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: job-data
        path: Jobs-Library/known_jobs.json
        retention-days: 30
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: job-monitor-logs
        path: Jobs-Library/job_monitor.log
        retention-days: 3
